name: tech_nest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_bloc:
  dartz:
  get_it:
  email_validator:
  url_launcher:
  go_router:
  dio:
  shared_preferences:
  equatable:
  pinput:
  flutter_spinkit:
  awesome_dialog:
  google_sign_in:
  image_picker:
  flutter_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
