// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe0YRsGORK5JNXRUF15yteqbe2yqLjBIg',
    appId: '1:501990395298:web:6308652453221708a5f6fb',
    messagingSenderId: '501990395298',
    projectId: 'tech-nest-49181',
    authDomain: 'tech-nest-49181.firebaseapp.com',
    storageBucket: 'tech-nest-49181.firebasestorage.app',
    measurementId: 'G-T64LEPX4KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQEt5g46ZNHlYZ9iNiFDdBHzc5ZScPA38',
    appId: '1:501990395298:android:d3d9519683193943a5f6fb',
    messagingSenderId: '501990395298',
    projectId: 'tech-nest-49181',
    storageBucket: 'tech-nest-49181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoh6290VZ7Pe6tBKViZKqL_qef2WzU3BA',
    appId: '1:501990395298:ios:c4e0ddc665bee6fda5f6fb',
    messagingSenderId: '501990395298',
    projectId: 'tech-nest-49181',
    storageBucket: 'tech-nest-49181.firebasestorage.app',
    iosBundleId: 'com.example.techNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoh6290VZ7Pe6tBKViZKqL_qef2WzU3BA',
    appId: '1:501990395298:ios:c4e0ddc665bee6fda5f6fb',
    messagingSenderId: '501990395298',
    projectId: 'tech-nest-49181',
    storageBucket: 'tech-nest-49181.firebasestorage.app',
    iosBundleId: 'com.example.techNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe0YRsGORK5JNXRUF15yteqbe2yqLjBIg',
    appId: '1:501990395298:web:7e812478aee29e1ba5f6fb',
    messagingSenderId: '501990395298',
    projectId: 'tech-nest-49181',
    authDomain: 'tech-nest-49181.firebaseapp.com',
    storageBucket: 'tech-nest-49181.firebasestorage.app',
    measurementId: 'G-J20WKLCYQF',
  );

}