
default_platform(:android)

platform :android do
  desc "Lane for Android Firebease App Distribution"
  lane :firebase_app_dist do
    sh "flutter clean"
    sh "flutter build apk --release --split-per-abi"
    firebase_app_distribution(
    app: "1:501990395298:android:d3d9519683193943a5f6fb",

    android_artifact_type: "APK",
    android_artifact_path: "C:\\Projects\\tech_nest\\build\\app\\outputs\\flutter-apk\\app-arm64-v8a-release.apk",
    testers: "marwanghareeb18@gmail.com",
    release_notes: "This is a test release for QA team and trusted testers."
    )
  end
end
