class ApiKeys {
  const ApiKeys._();

  static const String status = "status";
  static const String message = "message";
  static const String data = "data";
  static const String user = "user";
  static const String id = "id";
  static const String name = "name";
  static const String email = "email";
  static const String pass = "password";
  static const String role = "role";
  static const String description = "description";
  static const String price = "price";
  static const String stock = "stock";
  static const String categoryID = "category_id";
  static const String category = "category";
  static const String image = "image";
  static const String quantity = "quantity";
  static const String token = "token";
  static const String imgUrl = "image_url";
  static const String code = "verification_code";
  static const String newPass = "new_password";
  static const String provider = "provider";
  static const String socialId = "social_id";
  static const String profileImg = "profile_image";
  static const String profileImgUrl = "profile_image_url";
  static const String limit = "limit";
  static const String page = "page";
  static const String products = "products";
  static const String search = "search";
  static const String minPrice = "min_price";
  static const String maxPrice = "max_price";
  static const String sort = "sort";
  static const String order = "order";
  static const String searchQuery = "search_query";
  static const String productId = "product_id";
  static const String product = "product";
  static const String items = "items";
  static const String totalQuantity = "total_quantity";
  static const String totalPrice = "total_price";
  static const String deliveryCharges = "delivery_charges";
  static const String grandTotal = "grand_total";
}
