name: iOS-appetize-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          cache: true

      - run: flutter clean
      - run: flutter pub get

      - run: flutter build ios --no-codesign

      - run: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock

      - run: pod install --repo-update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: |
          mkdir -p build/appetize
          cp -R build/ios/iphoneos/Runner.app build/appetize/

      - uses: actions/upload-artifact@v4
        with:
          name: ios-appetize-build
          path: build/appetize/Runner.app