name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      # ======================
      # Flutter Setup FIRST
      # ======================
      - run: flutter clean

      - run: flutter pub get

      # 🔥 IMPORTANT STEP (creates Generated.xcconfig)
      - name: Prepare iOS project
        run: flutter build ios --no-codesign

      # ======================
      # CocoaPods AFTER build
      # ======================
      - name: Install Pods
        run: |
          cd ios
          pod install --repo-update

      # ======================
      # Build again clean
      # ======================
      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      # ======================
      # Create IPA
      # ======================
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload
          zip -r FlutterIpaExport.ipa Payload

      # ======================
      # Upload artifact
      # ======================
      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/iphoneos/FlutterIpaExport.ipa

      # ======================
      # Release
      # ======================
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "iOS build"
